{
 "title": "DOCKER LOGS",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "ERROR Logs Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(app) (\n    rate({app=~\"app1|app2\"} \n    | level =~\"crit|error|fatal\" [1m])\n)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "ERROR LOGS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"app1|app2\"} | level =~\"crit|fatal|error\""
    }
   ]
  },
  {
   "title": "Warn Logs Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(app) (\n    rate({app=~\"app1|app2\"} \n    | level =\"warn\" [1m])\n)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "WARN Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"app1|app2\"} | level =~\"warn\""
    }
   ]
  },
  {
   "title": "Info Logs Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(app) (\n    rate({app=~\"app1|app2\"} \n    | level =\"info\" [1m])\n)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "INFO Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"app1|app2\"} | level =~\"info\""
    }
   ]
  }
 ]
}