{
 "title": "Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Network_Receive_Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(rate(container_network_receive_bytes_total{name=~\"app1|app2|nginx\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network_Transit_Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\"app1|app2|nginx\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers Running For The Project",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\"app1|app2|nginx\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"app1|app2|nginx\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_cpu_usage_seconds_total{name=~\"app1|app2|nginx\"}[30s])\n) * 100\n",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}