{
 "title": "NGINX",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request Time Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"nginx\"} | json request_time"
    }
   ]
  },
  {
   "title": "No. Of Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({app=\"nginx\"} [1m]))"
    }
   ]
  },
  {
   "title": "Average Request Time Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(rate({app=\"nginx\"} | json | request_time!=\"\" | unwrap request_time [1m])) * 1000"
    }
   ]
  },
  {
   "title": "Upstream Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({app=\"nginx\"} |= \"upstream\" [5m]))",
     "legendFormat": "Upstream Error"
    }
   ]
  },
  {
   "title": "Top URL Routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (url) (count_over_time({app=\"nginx\"} | json | url!=\"\" [5m])))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Status Code Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status) (\nrate({app=\"nginx\"} | json | status!=\"\"[1m])\n)"
    }
   ]
  },
  {
   "title": "NGINX-ACCESS LOGS",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"nginx-access\"} |= ``"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"nginx-error\"} |= ``"
    }
   ]
  }
 ]
}