{
 "title": "Route Performance ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top 10 Slowest Routes (Avg Latency)",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, avg by(url) (avg_over_time({app=\"nginx\"} | json | __error__!=\"JSONParserErr\" | url!=\"\" | unwrap request_time [5m])))"
    }
   ]
  },
  {
   "title": "Requests per Route (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(url) (rate({app=\"nginx\"} | json | __error__!=\"JSONParserErr\" | url!=\"\" [1m]))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Latency per Route (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by(url) (avg_over_time({app=\"nginx\"} | json | __error__!=\"JSONParserErr\" | url!=\"\" | unwrap request_time [5m]))"
    }
   ]
  }
 ]
}